pull_request_rules:
  - name: Automate base image upgrade review process from Dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=Updated by Dependabot
      - label=packages/docker-base-images
      - base=main
      - -closed
      # Things start to blur when you use GH Actions.
      # see https://docs.mergify.io/conditions/#github-actions
      - status-success=Test and analyize image build
    actions:
      review:
        type: APPROVE
        message: |
           Approving @dependabot's pull request, this will only update the following tags: `develop`

           Maintainers have been advised to to create an new release regarding
           this base image upgrade as soon as possible for patches, including security fixes, and
           within the next 48-72 hours for minor releases.
           For major releases, expect breaking changes and notify your users accordingly before creating an new GitHub release.

           To learn more about this guideline, please read your `docs/release-management/automated-base-image-upgrades.md` or
           through <https://cdrs-docs.rtapp.tk/base-images-dependabot
           in case your copy of maintainers' docs go outdated.

           To automatically merge this, simply add `Ready to Ship` label
           after you review the changelog and appeoce it by yourself.

           --

           To control chaos cause by these automated merges, you need to
           manually merge this PR once you completed reviewed its
           release changelog. If you want chaos, please read your copy
           of `docs/post-repo-creation/mergify.md` or through <https://cdrs-docs.rtapp.tk/mergify>.
      assign:
        add_users:
          # Replace mine with your username.
          - AndreiJirohHaliliDev2006
  - name: Approve from an label
    conditions:
      - label=automation/mergify-approve-rule
      - -label=WIP
      - -label=Blocked from Merging
    actions:
      review:
        type: APPROVE
        message: |
          Hey, @{{author}}! Your PR is approved through an automated process using Mergify.
          You or they will merge it soon, either manually or when the
          `Ready to Ship` label is being added.
      label:
        remove: [ "automation/mergify-approve-rule" ]
  - name: Automagically comment for merging when LGTM
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      # Things start to blur when you use GH Actions.
      # see https://docs.mergify.io/conditions/#github-actions
      - status-success=Test and analyize image build
      - -label=Blocked from Merging
      - -label=WIP
      - -label=Ready to Ship
      - -merged
      - -closed
    actions:
      label:
        add: [ "Ready to Ship" ]
      comment:
        message: Now shipping into the `develop` Docker image tag. (The Merge bot action might take an while to merge this automagically.)
