name: "Docker CI (image releaser)"

env:
  # Change this to match GITHUB_REPOSITORY or any name you want.
  # But please be reminded that Docker images only support
  # lowercased letters as as long as there's an label called
  # org.opencontainers.image.source.
  repository: kubernetes-starter
  namespace: code-server-boilerplates
  namespace_dockerhub: codeserverboilerplates

on:
  release:
    type: [published]

jobs:
  # For prereleases, push to beta tag.
  publish-to-beta:
     name: Release to beta
     runs-on: "ubuntu-latest"
     if: ${{ github.event.release.prerelease == "true" }}
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"

       - name: Generate metadata for Docker builds
         id: meta
         uses: docker/metadata-action@v3
         with:
           images: |
             ${{ env.namespace_dockerhub }}/${{ env.repository }}
             quay.io/${{ env.namespace }}/${{ env.repository }}
             ghcr.io/${{ env.namespace }}/${{ env.repository }}
           tags: |
             type=semver,pattern={{version}}
             type=raw,value=beta
           flavor: |
             latest=false

       - name: Print out values
         env:
           METADATA_OUTPUTS: ${{ toJSON(steps.meta.outputs) }}
         run: "echo '$METADATA_OUTPUTS'"

       # Setup QEMU for multiarch builds
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       # and of course, we need to setup Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         with:
           driver-opts: "image=moby/buildkit:master,network=host"

       # repeat this for other registries you want to use
       # especially the official Docker Hub Registry
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           # change the username into yours if not using our bot
           username: RecapTimeBot
           # you need to manually add our bot with write access if you use our PAT
           password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
       - name: Login to Red Hat Quay Container Registry
         uses: docker/login-action@v1
         with:
           registry: quay.io
           # change the username into yours if not using our bot
           username: ${{ secrets.QUAYIO_USERNAME }}
           # may not work on personal accounts if using our PAT
           # we may try soon
           password: ${{ secrets.QUAYIO_PASSWORD }}

       - name: Build and push to GHCR + DockerHub and RHQC
         id: image-build
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           context: .
           platforms: linux/amd64
  publish-to-stable:
     name: Release to stable
     runs-on: "ubuntu-latest"
     if: ${{ github.event.release.prerelease != "true" }}
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"

       - name: Generate metadata for Docker builds
         id: meta
         uses: docker/metadata-action@v3
         with:
           images: |
             ${{ env.namespace_dockerhub }}/${{ env.repository }}
             quay.io/${{ env.namespace }}/${{ env.repository }}
             ghcr.io/${{ env.namespace }}/${{ env.repository }}
           tags: |
             type=semver,pattern={{version}}
           flavor: |
             latest=true

       - name: Print out values
         env:
           METADATA_OUTPUTS: ${{ toJSON(steps.meta.outputs) }}
         run: "echo '$METADATA_OUTPUTS'"

       # Setup QEMU for multiarch builds
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       # and of course, we need to setup Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         with:
           driver-opts: "image=moby/buildkit:master,network=host"

       # repeat this for other registries you want to use
       # especially the official Docker Hub Registry
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           # change the username into yours if not using our bot
           username: RecapTimeBot
           # you need to manually add our bot with write access if you use our PAT
           password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
       - name: Login to Red Hat Quay Container Registry
         uses: docker/login-action@v1
         with:
           registry: quay.io
           # change the username into yours if not using our bot
           username: ${{ secrets.QUAYIO_USERNAME }}
           # may not work on personal accounts if using our PAT
           # we may try soon
           password: ${{ secrets.QUAYIO_PASSWORD }}

       - name: Build and push to GHCR + DockerHub and RHQC
         id: image-build
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           context: .
           platforms: linux/amd64
