name: "Docker CI (image development)"

env:
  # Change this to match GITHUB_REPOSITORY or any name you want.
  # But please be reminded that Docker images only support
  # lowercased letters as as long as there's an label called
  # org.opencontainers.image.source.
  repository: code-server-boilerplates/kubernetes-cluster-admin

on:
  push:
    paths:
      - "Dockerfile"
      - ".trigger-rebuild"
      - ".dockerignore"
      - "toolkits/packages/scripts/**"
  pull_request:
    branches: [ main ]

jobs:
  test-image-builds:
     name: Test and analyize image build
     runs-on: "ubuntu-latest"
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"

       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         with:
           driver-opts: "image=moby/buildkit:master,network=host"

       - name: Install Dive
         run: |
           wget https://github.com/wagoodman/dive/releases/download/v0.10.0/dive_0.10.0_linux_amd64.deb -O $HOME/work/_temp/dive_linux_amd64.deb
           sudo apt install $HOME/work/_temp/dive_linux_amd64.deb

       - name: Build image
         uses: docker/build-push-action@v2
         id: build
         with:
           context: .
           platforms: linux/amd64,linux/arm64

       - name: Check wasted space
         run: |
           echo ::debug::${{ toJSON(steps) }}
           CI=true dive ${{ steps.build.outputs.digest }} --source docker://ghcr.io/${{ env.repository }} || true

  publish-to-dev:
     name: Publish as canary
     needs: [ test-image-builds ]
     runs-on: "ubuntu-latest"
     if: ${{ github.ref == 'refs/heads/main' && !github.event.issue.pull_request }}
     steps:
       - name: "Create checkmates"
         uses: "actions/checkout@v2"

       # Setup QEMU for multiarch builds
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       # and of course, we need to setup Buildx
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
         with:
           driver-opts: "image=moby/buildkit:master,network=host"

       # repeat this for other registries you want to use
       # especially the official Docker Hub Registry
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
           registry: ghcr.io
           # change the username into yours if not using our bot
           username: RecapTimeBot
           # may not work on personal accounts if using our PAT
           # we may try soon
           password: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
       - name: Login to Red Hat Quay Container Registry
         uses: docker/login-action@v1
         with:
           registry: quay.io
           # change the username into yours if not using our bot
           username: ${{ secrets.QUAYIO_USERNAME }}
           # may not work on personal accounts if using our PAT
           # we may try soon
           password: ${{ secrets.QUAYIO_PASSWORD }}

       # after building, we may retag them for DockerHub instead
       # of building again
       - name: Build and push to GHCR + DockerHub and RHQC
         id: image-build
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: |
             ghcr.io/${{ env.repository }}:develop
             quay.io/${{ env.repository }}:develop
           context: .
           platforms: linux/amd64,linux/arm64
