on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - ".github/labels.json"

name: Sync labels from labels.json

jobs:
  labels:
    name: Add needed labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1.0.0
      - uses: lannonbr/issue-label-manager-action@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SERVICE_ACCOUNT_API_KEY }}
